#!/usr/bin/env python3
"""
encode_curved_rowcol.py
Reads an ASCII instance of the puzzle (curved thermometers) and generates domain.lp.

Input supports:
 - Bulbs: U D L R
 - Straight segments: ^ v < >
 - Curved segments: 0 1 2 3  (└ ┏ ┐ ┘ clockwise)

Output: facts in (row, col) format with indices 0..N-1:
  dim(N).
  bulb(Row,Col,Dir).    Dir = up|down|left|right
  seg(Row,Col,Dir).
  curve(Row,Col,Type).  Type = 0..3
  colCount(Col,Num).
  rowCount(Row,Num).

Usage:
  python3 encode_curved_rowcol.py input.txt domain.lp
"""
import sys

if len(sys.argv) != 3:
    print("Use: python3 encode_curved_rowcol.py entrada.txt domain.lp")
    sys.exit(1)

infile = sys.argv[1]
outfile = sys.argv[2]

bulb_map = {'U': 'up', 'D': 'down', 'L': 'left', 'R': 'right'}
seg_map  = {'^': 'up', 'v': 'down', '<': 'left', '>': 'right'}
curve_chars = {'0':0, '1':1, '2':2, '3':3}

with open(infile, 'r', encoding='utf-8') as f:
    lines = [line.rstrip('\n') for line in f.readlines()]

if len(lines) < 3:
    print("Invalid input: too few lines.")
    sys.exit(1)

col_line = lines[-2].strip()
row_line = lines[-1].strip()
grid_lines = lines[:-2]
n = len(grid_lines)


for i, row in enumerate(grid_lines, start=1):
    if len(row) != n:
        print(f"Row {i} has length {len(row)}, which differs from n={n}.")
        sys.exit(1)


try:
    col_counts = [int(x) for x in col_line.split()]
    row_counts = [int(x) for x in row_line.split()]
except ValueError:
    print("Invalid counters")
    sys.exit(1)

if len(col_counts) != n or len(row_counts) != n:
    print("Diferent from n.")
    sys.exit(1)

with open(outfile, 'w', encoding='utf-8') as out:
    out.write(f"% Generated by encode_curved_rowcol.py from {infile}\n")
    out.write(f"dim({n}).\n\n")

    for row, line in enumerate(grid_lines):
        for col, ch in enumerate(line):
            if ch in bulb_map:
                out.write(f"bulb({row},{col},{bulb_map[ch]}).\n")
            elif ch in seg_map:
                out.write(f"seg({row},{col},{seg_map[ch]}).\n")
            elif ch in curve_chars:
                out.write(f"curve({row},{col},{curve_chars[ch]}).\n")
            else:
                print(f"Unknown character ‘{ch}’ at ({row},{col}).")
                sys.exit(1)
    out.write("\n")
    for i, num in enumerate(col_counts):
        out.write(f"colCount({i},{num}).\n")
    out.write("\n")
    for i, num in enumerate(row_counts):
        out.write(f"rowCount({i},{num}).\n")

print(f"Wrote domain facts to {outfile}")
