#!/usr/bin/env python3
"""
encode_curved_rowcol.py
Lee una instancia ASCII del puzzle (curved thermometers) y genera domain.lp.
Entrada soporta:
 - Bulbos: U D L R
 - Segmentos rectos: ^ v < >
 - Curvas: 0 1 2 3  (└ ┏ ┐ ┘ en sentido horario)
Salida: hechos en formato (row,col) con índices 0..N-1:
  dim(N).
  bulb(Row,Col,Dir).   Dir = up|down|left|right
  seg(Row,Col,Dir).
  curve(Row,Col,Type). Type = 0..3
  colCount(Col,Num).
  rowCount(Row,Num).
Uso:
  python3 encode_curved_rowcol.py entrada.txt domain.lp
"""
import sys

if len(sys.argv) != 3:
    print("Uso: python3 encode_curved_rowcol.py entrada.txt domain.lp")
    sys.exit(1)

infile = sys.argv[1]
outfile = sys.argv[2]

bulb_map = {'U': 'up', 'D': 'down', 'L': 'left', 'R': 'right'}
seg_map  = {'^': 'up', 'v': 'down', '<': 'left', '>': 'right'}
curve_chars = {'0':0, '1':1, '2':2, '3':3}

with open(infile, 'r', encoding='utf-8') as f:
    lines = [line.rstrip('\n') for line in f.readlines()]

if len(lines) < 3:
    print("Entrada inválida: muy pocas líneas.")
    sys.exit(1)

col_line = lines[-2].strip()
row_line = lines[-1].strip()
grid_lines = lines[:-2]
n = len(grid_lines)

# comprobar cuadrado
for i, row in enumerate(grid_lines, start=1):
    if len(row) != n:
        print(f"Fila {i} tiene longitud {len(row)} distinta de n={n}.")
        sys.exit(1)

# parseo contadores
try:
    col_counts = [int(x) for x in col_line.split()]
    row_counts = [int(x) for x in row_line.split()]
except ValueError:
    print("Contadores inválidos.")
    sys.exit(1)

if len(col_counts) != n or len(row_counts) != n:
    print("Número de contadores distinto de n.")
    sys.exit(1)

with open(outfile, 'w', encoding='utf-8') as out:
    out.write(f"% Generated by encode_curved_rowcol.py from {infile}\n")
    out.write(f"dim({n}).\n\n")

    for row, line in enumerate(grid_lines):
        for col, ch in enumerate(line):
            if ch in bulb_map:
                out.write(f"bulb({row},{col},{bulb_map[ch]}).\n")
            elif ch in seg_map:
                out.write(f"seg({row},{col},{seg_map[ch]}).\n")
            elif ch in curve_chars:
                out.write(f"curve({row},{col},{curve_chars[ch]}).\n")
            else:
                print(f"Caracter desconocido '{ch}' en ({row},{col}).")
                sys.exit(1)
    out.write("\n")
    for i, num in enumerate(col_counts):
        out.write(f"colCount({i},{num}).\n")
    out.write("\n")
    for i, num in enumerate(row_counts):
        out.write(f"rowCount({i},{num}).\n")

print(f"Wrote domain facts to {outfile}")
