#!/usr/bin/env python3
"""
Reads an ASCII instance of the Thermometers puzzle and generates domain.lp containing facts.
Uses 0..N-1 coordinates in (row, col) format to remain compatible with decode.py
"""
import sys

# Ensure the script is called with exactly two arguments
if len(sys.argv) != 3:
    print("Use: python3 encode.py entrada.txt domain.lp")
    sys.exit(1)

infile = sys.argv[1]
outfile = sys.argv[2]

# Dictionaries that map ASCII symbols to their corresponding directions.
# 'bulb_map' is used for thermometer bulbs (U, D, L, R),
# and 'seg_map' for thermometer segments (^, v, <, >).
# The mapped values ('up', 'down', 'left', 'right') are used in the output facts.
bulb_map = {'U': 'up', 'D': 'down', 'L': 'left', 'R': 'right'}
seg_map = {'^': 'up', 'v': 'down', '<': 'left', '>': 'right'}

# Open the input file (ASCII puzzle) and read all lines, stripping newline characters.
# Each element in 'lines' corresponds to one row of the input grid.
with open(infile, 'r', encoding='utf-8') as f:
    lines = [line.rstrip('\n') for line in f.readlines()]

# Ensure the file has at least 3 lines: the grid plus two lines of row/column counts.
if len(lines) < 3:
    print("Invalid input: too few lines.")
    sys.exit(1)

# The last two lines contain the numeric constraints:
#   - Second to last line - column counts
col_line = lines[-2].strip()
#  Last line - row counts
row_line = lines[-1].strip()
# All previous lines form the puzzle grid.
grid_lines = lines[:-2]
# Determine the grid size (n x n).
n = len(grid_lines)


# Verify that the grid is square (n x n).
for i, row in enumerate(grid_lines, start=1):
    if len(row) != n:
        print(f"Row {i} has length {len(row)}, which differs from n={n}.")
        sys.exit(1)

# Parse column and row counters from the last two lines.
# Convert each space-separated value to an integer and validate their count.
try:
    col_counts = [int(x) for x in col_line.split()]
    row_counts = [int(x) for x in row_line.split()]
except ValueError:
    print("Row/column counters must be integers separated by spaces.")
    sys.exit(1)

if len(col_counts) != n or len(row_counts) != n:
    print("Number of counters does not match grid size n.")
    sys.exit(1)

# Open the output file and write the generated logic program facts.
with open(outfile, 'w', encoding='utf-8') as out:
    out.write(f"% Generated by encode.py from {infile}\n")
    out.write(f"dim({n}).\n\n")

    # Write a 'bulb' fact for thermometer bulbs and a 'seg' fact for segments.
    for row, line in enumerate(grid_lines):
        for col, ch in enumerate(line):
            if ch in bulb_map:
                out.write(f"bulb({row},{col},{bulb_map[ch]}).\n")
            elif ch in seg_map:
                out.write(f"seg({row},{col},{seg_map[ch]}).\n")
            else:
                print(f"Unknown character '{ch}' at ({row},{col}).")
                sys.exit(1)
    out.write("\n")

    # Write column and row count facts.
    for i, num in enumerate(col_counts):
        out.write(f"colCount({i},{num}).\n")
    out.write("\n")

    
    for i, num in enumerate(row_counts):
        out.write(f"rowCount({i},{num}).\n")

print(f"Wrote domain facts to {outfile}")
